### ISSUE TITLE
Command failed with error 112 (WriteConflict) occurred

### ISSUE THREAD

**Issue by kaeskers** [spring-projects-experimental/spring-batch-experimental#4]
Hello Team,

When Spring Batch jobs run concurrently, for example, a batch job that runs every minute and another that runs every five minutes, a WriteConflict error occurs when they run together at the five-minute mark. Is there a solution to this issue?

{
  "eventTime": "2024-06-24T05:52:00.946+0000",
  "level": "ERROR",
  "msg": "Unexpected error occurred in scheduled task",
  "file": "org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler:95",
  "func": "handleError",
  "exception": "org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 112 (WriteConflict): 'WriteConflict error: this operation conflicted with another operation. Please retry your operation or multi-document transaction.' on server ${server-info}:27016. The full response is {\"errorLabels\": [\"TransientTransactionError\"], \"ok\": 0.0, \"errmsg\": \"WriteConflict error: this operation conflicted with another operation. Please retry your operation or multi-document transaction.\", \"code\": 112, \"codeName\": \"WriteConflict\", \"$clusterTime\": {\"clusterTime\": {\"$timestamp\": {\"t\": 1719208320, \"i\": 3}}, \"signature\": {\"hash\": {\"$binary\": {\"base64\": \"V25me8QBTzZa9w9dDeg9pdZM02w=\", \"subType\": \"00\"}}, \"keyId\": 7340701495207133190}}, \"operationTime\": {\"$timestamp\": {\"t\": 1719208320, \"i\": 3}}, \"recoveryToken\": {}}\n\tat org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:135)\n\tat org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2993)\n\tat org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:2876)\n\tat org.springframework.data.mongodb.core.MongoTemplate.doFindAndModify(MongoTemplate.java:2731)\n\tat org.springframework.data.mongodb.core.MongoTemplate.findAndModify(MongoTemplate.java:1089)\n\tat org.springframework.data.mongodb.core.MongoTemplate.findAndModify(MongoTemplate.java:1058)\n\tat org.springframework.batch.experimental.core.repository.dao.MongoSequenceIncrementer.nextLongValue(MongoSequenceIncrementer.java:51)\n\tat org.springframework.batch.experimental.core.repository.dao.MongoJobInstanceDao.createJobInstance(MongoJobInstanceDao.java:74)\n\tat org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:168)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)\n\tat org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)\n\tat org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)\n\tat org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)\n\tat org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean.lambda$getObject$0(AbstractJobRepositoryFactoryBean.java:204)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)\n\tat org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)\n\tat jdk.proxy2/jdk.proxy2.$Proxy80.createJobExecution(Unknown Source)\n\tat org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:145)\n\tat org.springframework.batch.core.launch.support.TaskExecutorJobLauncher.run(TaskExecutorJobLauncher.java:59)\n\tat com.xxxx.DynamicBatchConfiguration.lambda$init$0(DynamicBatchConfiguration.java:55)\n\tat org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)\n\tat org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:96)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: com.mongodb.MongoCommandException: Command failed with error 112 (WriteConflict): 'WriteConflict error: this operation conflicted with another operation. Please retry your operation or multi-document transaction.' on server ${server-info}:27016. The full response is {\"errorLabels\": [\"TransientTransactionError\"], \"ok\": 0.0, \"errmsg\": \"WriteConflict error: this operation conflicted with another operation. Please retry your operation or multi-document transaction.\", \"code\": 112, \"codeName\": \"WriteConflict\", \"$clusterTime\": {\"clusterTime\": {\"$timestamp\": {\"t\": 1719208320, \"i\": 3}}, \"signature\": {\"hash\": {\"$binary\": {\"base64\": \"V25me8QBTzZa9w9dDeg9pdZM02w=\", \"subType\": \"00\"}}, \"keyId\": 7340701495207133190}}, \"operationTime\": {\"$timestamp\": {\"t\": 1719208320, \"i\": 3}}, \"recoveryToken\": {}}\n\tat com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:205)\n\tat com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:454)\n\tat com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:372)\n\tat com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)\n\tat com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:765)\n\tat com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)\n\tat com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:209)\n\tat com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115)\n\tat com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83)\n\tat com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:74)\n\tat com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:299)\n\tat com.mongodb.internal.operation.SyncOperationHelper.lambda$executeRetryableWrite$9(SyncOperationHelper.java:243)\n\tat com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$0(SyncOperationHelper.java:127)\n\tat com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)\n\tat com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$1(SyncOperationHelper.java:126)\n\tat com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)\n\tat com.mongodb.internal.operation.SyncOperationHelper.withSourceAndConnection(SyncOperationHelper.java:125)\n\tat com.mongodb.internal.operation.SyncOperationHelper.lambda$executeRetryableWrite$10(SyncOperationHelper.java:229)\n\tat com.mongodb.internal.operation.SyncOperationHelper.lambda$decorateWriteWithRetries$11(SyncOperationHelper.java:283)\n\tat com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)\n\tat com.mongodb.internal.operation.SyncOperationHelper.executeRetryableWrite(SyncOperationHelper.java:255)\n\tat com.mongodb.internal.operation.BaseFindAndModifyOperation.execute(BaseFindAndModifyOperation.java:80)\n\tat com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:173)\n\tat com.mongodb.client.internal.MongoCollectionImpl.executeFindOneAndUpdate(MongoCollectionImpl.java:761)\n\tat com.mongodb.client.internal.MongoCollectionImpl.findOneAndUpdate(MongoCollectionImpl.java:755)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281)\n\tat org.springframework.data.mongodb.SessionAwareMethodInterceptor.invoke(SessionAwareMethodInterceptor.java:119)\n\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)\n\tat org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)\n\tat jdk.proxy2/jdk.proxy2.$Proxy110.findOneAndUpdate(Unknown Source)\n\tat org.springframework.data.mongodb.core.MongoTemplate$FindAndModifyCallback.doInCollection(MongoTemplate.java:3183)\n\tat org.springframework.data.mongodb.core.MongoTemplate$FindAndModifyCallback.doInCollection(MongoTemplate.java:3141)\n\tat org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:2873)\n\t... 32 common frames omitted\n",
  "thread": "batch-scheduler-4"
}

Thanks

**Comment by fmbenhassine** [comment]
This issue is not related to any experimental feature. The issue tracker here is only for issues related to the experimental features. Please ask your question on StackOverflow or open a discussion on the repository of the main project: https://github.com/spring-projects/spring-batch/discussions. Thank you.
